### ISSUE TITLE
Got error when invoking echo function by python!

### ISSUE THREAD

**Issue by czzmmc** [apache/incubator-teaclave#305]
Hi, I use simulation mode and I successfully run the 7 services. When I executed python code builtin_echo.py, I got a openssl error message like below.

Traceback (most recent call last):
  File "builtin_echo.py", line 199, in <module>
    main()
  File "builtin_echo.py", line 191, in main
    rt = example.echo(message)
  File "builtin_echo.py", line 158, in echo
    verify_report(AS_ROOT_CA_CERT_PATH, ENCLAVE_INFO_PATH, cert, "authentication")
  File "incubator-teaclave/sdk/python/teaclave.py", line 41, in verify_report
    signing_cert = load_certificate(FILETYPE_ASN1, signing_cert)
  File ".local/lib/python3.6/site-packages/OpenSSL/crypto.py", line 1794, in load_certificate
    _raise_current_error()
  File ".local/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('asn1 encoding routines', 'ASN1_get_object', 'header too long')]

I know I am using demo certs. Do I need to generate those files by myself? Is it related to my openssl lib version or something like that?

**Comment by mssun** [comment]
If you are using simulation mode, there is no attestation. Please set the env var `SGX_MODE` before starting the example by `export SGX_MODE=SW`.

See: https://github.com/apache/incubator-teaclave/blob/master/sdk/python/teaclave.py#L202

I'll update the doc later.
