### ISSUE TITLE
File access problem in builtin function

### ISSUE THREAD

**Issue by Mengyuan-L** [apache/incubator-teaclave#458]
Hi all, 

I have met some problems about running some builtin functions (e.g., "builtin_private_join_and_compute.py", "builtin_ordered_set_intersect.py", and "builtin_gbdt_train.py" ).

The error looks like:

```
Traceback (most recent call last):
  File "builtin_private_join_and_compute.py", line 238, in <module>
    main()
  File "builtin_private_join_and_compute.py", line 228, in main
    result_user0 = user0.get_task_result(task_id)
  File "builtin_private_join_and_compute.py", line 196, in get_task_result
    return bytes(client.get_task_result(task_id))
  File "/home/mengyuan/incubator-teaclave/sdk/python/teaclave.py", line 436, in get_task_result
    return response["content"]["result"]["result"]["Ok"]["return_value"]
KeyError: 'Ok'
```

Any ideas?
Thanks

**Comment by Mengyuan-L** [comment]
I found the reason for these kinds of problems.

The reason is that the execution service inside the docker cannot correctly access the input files as well as the output files.

One can fix this problem by changing 
```
INPUT_FILE_URL_PREFIX = "http://localhost:6789/fixtures/functions/ordered_set_intersect/"
OUTPUT_FILE_URL_PREFIX = "http://localhost:6789/fixtures/functions/ordered_set_intersect/"
```

to 

```
INPUT_FILE_URL_PREFIX = "http://teaclave-file-service:6789/fixtures/functions/ordered_set_intersect/"
OUTPUT_FILE_URL_PREFIX = "http://teaclave-file-service:6789/fixtures/functions/ordered_set_intersect/"
```

The domain name "teaclave-file-service" can be found via `$ docker ps`
you can get the domain name for teaclave file service under the "NAMES" column like this:

CONTAINER ID   IMAGE              COMMAND                  CREATED             STATUS              PORTS             NAMES
XXXXXXXX       python:3          "./scripts/simple_ht…"    1 days ago          Up 1 days            -             teaclave-file-service


Note that in a real-world case, the url or the input files should be provided by the user. In the built-in example, the developer embeds those files for test usage and we may use our own files here.
